Repository Cloud-Engineering2/cinebox, pull requests merged in 2025-02, with the labels that each got.

#1 Feat: 예외 처리 기능 추가
  src/main/java/cinebox/common/exception/BaseException.java
  src/main/java/cinebox/common/exception/ErrorResponse.java
  src/main/java/cinebox/common/exception/ExceptionMessage.java
  src/main/java/cinebox/common/exception/GlobalExceptionHandler.java
  src/main/java/cinebox/common/exception/movie/NotFoundMovieException.java
  src/main/java/cinebox/common/exception/user/NotFoundUserException.java
Labels: ✨feature

#2 Feat: 영화 등록 기능 구현
  src/main/java/cinebox/common/enums/MovieStatus.java
  src/main/java/cinebox/common/exception/ExceptionMessage.java
  src/main/java/cinebox/common/exception/movie/DuplicatedMovieException.java
  src/main/java/cinebox/controller/MovieController.java
  src/main/java/cinebox/dto/request/MovieRequest.java
  src/main/java/cinebox/dto/response/MovieResponse.java
  src/main/java/cinebox/entity/Movie.java
  src/main/java/cinebox/repository/MovieRepository.java
  src/main/java/cinebox/service/MovieService.java
  src/main/java/cinebox/service/MovieServiceImpl.java
Labels: ✨feature

#6 Feat: 영화 조회 기능 구현
  src/main/java/cinebox/controller/MovieController.java
  src/main/java/cinebox/repository/MovieRepository.java
  src/main/java/cinebox/service/MovieService.java
  src/main/java/cinebox/service/MovieServiceImpl.java
Labels: ✨feature

#7 Feat: 상영관 및 좌석 데이터 기본 생성
  src/main/java/cinebox/DataInitializer.java
  src/main/java/cinebox/entity/Auditorium.java
  src/main/java/cinebox/entity/Seat.java
  src/main/java/cinebox/repository/AuditoriumRepository.java
  src/main/java/cinebox/repository/SeatRepository.java
Labels: ✨feature

#10 Feat(#9): Edit movie
  src/main/java/cinebox/common/exception/ExceptionMessage.java
  src/main/java/cinebox/common/exception/GlobalExceptionHandler.java
  src/main/java/cinebox/common/exception/movie/MovieDeleteFailedException.java
  src/main/java/cinebox/controller/MovieController.java
  src/main/java/cinebox/dto/request/MovieRequest.java
  src/main/java/cinebox/dto/validation/CreateGroup.java
  src/main/java/cinebox/entity/Movie.java
  src/main/java/cinebox/service/MovieService.java
  src/main/java/cinebox/service/MovieServiceImpl.java
Labels: ✨feature

#19 Feat(#13): movie crud auth
  src/main/java/cinebox/common/exception/ExceptionMessage.java
  src/main/java/cinebox/common/exception/GlobalExceptionHandler.java
  src/main/java/cinebox/controller/MovieController.java
  src/main/java/cinebox/security/JwtTokenProvider.java
  src/main/java/cinebox/security/SecurityConfig.java
  src/main/java/cinebox/service/MovieServiceImpl.java
Labels: ✨feature

#20 Fix(#16): retrieve seat
  src/main/java/cinebox/common/exception/ExceptionMessage.java
  src/main/java/cinebox/common/exception/auditorium/NotFoundAuditoriumException.java
  src/main/java/cinebox/common/exception/screen/NotFoundScreenException.java
  src/main/java/cinebox/controller/BookingController.java
  src/main/java/cinebox/controller/SeatController.java
  src/main/java/cinebox/dto/response/AuditoriumResponse.java
  src/main/java/cinebox/dto/response/BookingSeatResponse.java
  src/main/java/cinebox/dto/response/ScreenResponseTest.java
  src/main/java/cinebox/dto/response/SeatResponse.java
  src/main/java/cinebox/dto/response/ShowtimeWithSeatsResponse.java
  src/main/java/cinebox/entity/BookingSeat.java
  src/main/java/cinebox/repository/ScreenRepository.java
  src/main/java/cinebox/repository/ScreenRepositoryTest.java
  src/main/java/cinebox/repository/SeatRepository.java
  src/main/java/cinebox/service/BookingService.java
  src/main/java/cinebox/service/SeatService.java
  src/main/java/cinebox/service/SeatServiceImpl.java
Labels: 🔨 Fix, ✨ Feature

#21 Feat(#17)/booking crud
  src/main/java/cinebox/common/exception/BaseException.java
  src/main/java/cinebox/common/exception/ExceptionMessage.java
  src/main/java/cinebox/common/exception/booking/AlreadyBookedSeatsException.java
  src/main/java/cinebox/common/exception/booking/NotFoundScreenException.java
  src/main/java/cinebox/common/exception/booking/NotFoundSeatException.java
  src/main/java/cinebox/common/exception/booking/SeatAlreadyBookedException.java
  src/main/java/cinebox/controller/BookingController.java
  src/main/java/cinebox/dto/BookingSeatDTO.java
  src/main/java/cinebox/dto/request/BookingRequest.java
  src/main/java/cinebox/dto/response/BookingResponse.java
  src/main/java/cinebox/entity/Booking.java
  src/main/java/cinebox/entity/BookingSeat.java
  src/main/java/cinebox/entity/Screen.java
  src/main/java/cinebox/repository/BookingRepository.java
  src/main/java/cinebox/repository/BookingSeatRepository.java
  src/main/java/cinebox/repository/ScreenRepository.java
  src/main/java/cinebox/repository/SeatRepository.java
  src/main/java/cinebox/repository/UserRepository.java
  src/main/java/cinebox/service/BookingService.java
Labels: ✨ Feature

#14 Feature(#18): review CRUD
  src/main/java/cinebox/common/exception/ExceptionMessage.java
  src/main/java/cinebox/common/exception/review/NotFoundReviewException.java
  src/main/java/cinebox/controller/ReviewController.java
  src/main/java/cinebox/controller/UserController.java
  src/main/java/cinebox/dto/request/ReviewRequest.java
  src/main/java/cinebox/dto/response/ReviewResponse.java
  src/main/java/cinebox/entity/Review.java
  src/main/java/cinebox/repository/ReviewRepository.java
  src/main/java/cinebox/security/JwtTokenProvider.java
  src/main/java/cinebox/security/PrincipalDetailsService.java
  src/main/java/cinebox/security/SecurityConfig.java
  src/main/java/cinebox/service/ReviewService.java
  src/main/java/cinebox/service/UserService.java
Labels: ✨ Feature

#26 Feat(#12): Batch Service를 통한 영화 등록
  src/main/java/cinebox/CineboxApplication.java
  src/main/java/cinebox/dto/response/KmdbResponse.java
  src/main/java/cinebox/dto/response/KobisMovieListResponse.java
  src/main/java/cinebox/entity/Movie.java
  src/main/java/cinebox/repository/MovieRepository.java
  src/main/java/cinebox/service/MovieBatchService.java
Labels: ✨ Feature

#29 Feat(#28): 상영 날짜 조회 구현
  src/main/java/cinebox/common/exception/ExceptionMessage.java
  src/main/java/cinebox/controller/MovieController.java
  src/main/java/cinebox/service/MovieService.java
  src/main/java/cinebox/service/MovieServiceImpl.java
Labels: ✨ Feature

#43 Refactor(#41): Screen 구조 변경 및 코드 형식 통일화
  src/main/java/cinebox/common/exception/ExceptionMessage.java
  src/main/java/cinebox/common/exception/booking/NotFoundScreenException.java
  src/main/java/cinebox/common/exception/screen/ScreenTimeConflictException.java
  src/main/java/cinebox/controller/ScreenController.java
  src/main/java/cinebox/dto/ScreenRequest.java
  src/main/java/cinebox/dto/request/ScreenRequest.java
  src/main/java/cinebox/dto/response/ScreenResponse.java
  src/main/java/cinebox/entity/Screen.java
  src/main/java/cinebox/repository/ScreenRepository.java
  src/main/java/cinebox/service/BookingService.java
  src/main/java/cinebox/service/ScreenService.java
Labels: 🛠️ Refactor

#52 Fix(#51): 영화 데이터 범위 조정
  src/main/java/cinebox/entity/Movie.java
  src/main/java/cinebox/service/MovieBatchService.java
Labels: 🐞 BugFix
